name: Flutter 32-bit Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 设置超时时间

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'  # 指定稳定版本
        channel: 'stable'
    
    - name: Clean build
      run: flutter clean
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build 32-bit APK
      run: flutter build apk --release --target-platform android-arm --verbose
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kazumi-32bit-release
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 5  # 自动清理旧构建
    
    - name: Show build info
      run: |
        echo "Build completed at $(date)"
        ls -lh build/app/outputs/flutter-apk/
