name: Build 32-bit APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PROJECT_ROOT: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Generate gradlew
        run: |
          cd "$PROJECT_ROOT/android"
          gradle wrapper --gradle-version 8.0

      - name: 强制创建并验证配置文件
        run: |
          echo "sdk.dir=$ANDROID_HOME" > "$PROJECT_ROOT/android/local.properties"
          echo "===== 配置文件内容 ====="
          cat "$PROJECT_ROOT/android/local.properties"
          echo "===== 完整目录结构 ====="
          ls -la "$PROJECT_ROOT/android/"

      - name: Build with debug info
        run: |
          cd "$PROJECT_ROOT/android"
          ./gradlew assembleRelease -PabiFilters=armeabi-v7a \
            --no-daemon \
            --stacktrace \
            --scan

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-32bit
          path: "$PROJECT_ROOT/android/app/build/outputs/apk/release/*.apk"
