name: Build 32-bit APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK  # ✅ 使用 Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Generate gradlew
        run: |
          cd android
          gradle wrapper --gradle-version 8.0

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > ./android/local.properties

      - name: Build 32-bit APK
        run: |
          cd android
          ./gradlew assembleRelease -PabiFilters=armeabi-v7a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-32bit
          path: android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
