name: Build Flutter 32-bit APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Build APK
        run: flutter build apk --release --target-platform android-arm

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-32bit
          path: build/app/outputs/flutter-apk/app-release.apk
