name: Build 32-bit APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Generate gradlew
        run: |
          cd android
          gradle wrapper --gradle-version 8.0

      - name: Create and verify local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > ./android/local.properties
          echo "=== File content ==="
          cat ./android/local.properties
          echo "=== File path ==="
          pwd && ls -la ./android/

      - name: Build 32-bit APK
        run: |
          cd android
          ./gradlew assembleRelease -PabiFilters=armeabi-v7a --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-32bit
          path: android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
